"""Initial migration

Revision ID: 0045bd336ef1
Revises: 
Create Date: 2024-06-28 11:37:41.642953

"""
from alembic import op
import sqlalchemy as sa
from app.models import JSONEncodedList


# revision identifiers, used by Alembic.
revision = '0045bd336ef1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('profile_picture', JSONEncodedList(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('religion', sa.String(length=64), nullable=True),
    sa.Column('politics', JSONEncodedList(), nullable=False),
    sa.Column('handling_money', JSONEncodedList(), nullable=False),
    sa.Column('health_living_space_cleanliness', sa.String(length=64), nullable=True),
    sa.Column('health_showering_frequency', sa.String(length=64), nullable=True),
    sa.Column('health_oral_care', sa.String(length=64), nullable=True),
    sa.Column('health_smoking', sa.String(length=64), nullable=True),
    sa.Column('health_alchohol_consumption', sa.String(length=64), nullable=True),
    sa.Column('health_marijuana_consumption', sa.String(length=64), nullable=True),
    sa.Column('gender_preference', JSONEncodedList(), nullable=False),
    sa.Column('religion_preference', JSONEncodedList(), nullable=False),
    sa.Column('politics_preference', JSONEncodedList(), nullable=False),
    sa.Column('handling_money_preference', JSONEncodedList(), nullable=False),
    sa.Column('health_living_space_cleanliness_preference', JSONEncodedList(), nullable=False),
    sa.Column('health_showering_frequency_preference', JSONEncodedList(), nullable=False),
    sa.Column('health_oral_care_preference', JSONEncodedList(), nullable=False),
    sa.Column('health_smoking_preference', JSONEncodedList(), nullable=False),
    sa.Column('health_alchohol_consumption_preference', JSONEncodedList(), nullable=False),
    sa.Column('health_marijuana_consumption_preference', JSONEncodedList(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('account_created', sa.DateTime(), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.Column('messages_received', sa.Integer(), nullable=True),
    sa.Column('google_id', sa.String(length=256), nullable=True),
    sa.Column('facebook_id', sa.String(length=256), nullable=True),
    sa.Column('account_status', sa.String(length=32), nullable=False),
    sa.Column('subscription_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
