"""user model migration

Revision ID: 205742d13cbd
Revises: 05f96f1138f1
Create Date: 2024-06-21 03:04:10.315981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205742d13cbd'
down_revision = '05f96f1138f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gender_preference',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('religion',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('politics',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('handling_money',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('hygiene',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('lifestyle_choices',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('religion_preference',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('politics_preference',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('handling_money_preference',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('hygiene_preference',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('lifestyle_choices_preference',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('lifestyle_choices_preference',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('hygiene_preference',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('handling_money_preference',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('politics_preference',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('religion_preference',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('lifestyle_choices',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('hygiene',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('handling_money',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('politics',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('religion',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('gender_preference',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
