"""user model migration2

Revision ID: 53f9ea45322a
Revises: 205742d13cbd
Create Date: 2024-06-21 03:06:35.587180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f9ea45322a'
down_revision = '205742d13cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('religion_weight',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('politics_weight',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('handling_money_weight',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hygiene_weight',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('lifestyle_choices_weight',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('lifestyle_choices_weight',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hygiene_weight',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('handling_money_weight',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('politics_weight',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('religion_weight',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
